Adoptopenjdk Linux images
jenkinsci/docker-agent pull request #172
Opened 2021-04-26 18:21 UTC by Fixmetal

As per https://github.com/jenkinsci/docker-inbound-agent/issues/216 I've tried to work out new `adoptopenjdk` based Docker images. Since I'm used to working with [hadolint](https://github.com/hadolint/hadolint), which helps me daily making bulletproof Docker images, I made several changes in order to be completely linted. I've made several commit messages with what has been changed against its [wiki](https://github.com/hadolint/hadolint/wiki) code.

Big whoop: Adoptopenjdk doesn't support debian stretch (oldstable) anymore (correct me if I'm wrong ofc) so I just deleted the whole directory. This is a major breaking change. It might be a better idea to just keep the old Docker Image with a big deprecation warning on it. Because of this, I've made changes to the `Makefile` in order to bring `buster` as the default `debian` image. `README.md` has been updated with proper image tags too.

I've made changes to `env.props` which seemed to me wrong (pointing to 4.6 when `master` is all on `4.7`.

Alpine adoptopenjdk image is `Alpine Linux 3.12.7` based so I've updated the `Makefile` to respect the new tag (old `3.9` new `3.12`)

The whole work seems good to me but obviously, the PR will challenge this especially since I'm a newcomer here :)
```
[work@maguro docker-agent]$ make test > /dev/null && echo $?
0
```

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-05-27 04:00 UTC, MarkEWaite reviewed
Thanks very much for the improvements!  Some comments for your consideration.

2021-05-27 04:00 UTC, MarkEWaite commented on README.md
> +
I'm not sure of the intent in listed the `FROM` clauses in the README, since the base image is described in the parenthesized expression after the text description of the tag
```suggestion
```

2021-05-27 15:10 UTC, slide requested changes

2021-05-27 15:10 UTC, slide commented on 11/alpine/Dockerfile
> +FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine-slim
curl is used pretty heavily, why not just have a new image instead of changing this one?

2021-05-27 15:10 UTC, slide commented on 8/alpine/Dockerfile
> +LABEL description="This is a base image, which provides the Jenkins agent executable (slave.jar)"
```suggestion
LABEL description="This is a base image, which provides the Jenkins agent executable (agent.jar)"
```

2021-05-28 07:50 UTC, Fixmetal commented on 11/alpine/Dockerfile
> +ARG OPENSSH_CLIENT_VER=8.3_p1-r2
I know it's tricky here because Alpine doesn't save other than the latest release on their repos but in this way, you can choose not to update the Docker Hub image in case something is wrong with those new packages.
Honestly, I don't know much about dependanbot capabilities, we should investigate.

2021-05-28 07:53 UTC, Fixmetal commented on 11/alpine/Dockerfile
> +FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine-slim
I personally dislike Alpine-based images but I feel an image should just contain what's needed, so shall we just install curl?

2021-05-28 07:54 UTC, Fixmetal commented on README.md
> +
Agreed, can be removed.

2021-05-28 15:47 UTC, slide commented on 11/alpine/Dockerfile
> +FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine-slim
We don't know what people are using from the current image, so replacing it with less stuff is not really great. It's like cutting multiple functions from an API that people have been using.

2021-06-06 21:27 UTC, Fixmetal commented on 11/alpine/Dockerfile
> +FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine-slim
I think I'm missing a point here. No alpine image has curl installed and the original `docker-agent` images delete it before committing the image.
See:

https://github.com/jenkinsci/docker-agent/blob/master/8/alpine/Dockerfile#L45
https://github.com/jenkinsci/docker-agent/blob/master/11/alpine/Dockerfile#L42

Could you please review?

2021-07-08 02:20 UTC, MarkEWaite commented on 11/alpine/Dockerfile
> +FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine-slim
You're correct @Fixmetal  that the Alpine image does not include curl.  We don't need to include curl since it was not there before.  My apologies for my mistake reading the Dockerfile and not confirming the actual image content.

2021-07-27 11:30 UTC, saper commented
I think most of the work has been done now kind of silently in #173 ? AdoptOpenJDK (soon "Adoptium Temurin") images are now used.

2021-07-27 12:07 UTC, closed without merging