WIP
jenkinsci/docker-agent pull request #310
Opened 2022-10-31 19:42 UTC by carpnick

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-11-01 13:39 UTC, lemeurherve reviewed
(Formatting suggestions only)

2022-11-01 13:39 UTC, lemeurherve commented on 17/bullseye/Dockerfile
> +RUN cp -r /opt/java/openjdk  /javaruntime
```suggestion
# Check docker bake target debian_jdk17_arm32
# Cannot get jlink to properly work, in the v7 environment.
# The jmods error above gets generated each time.
# Better to have a larger image than incorrect java binaries in 32bit arm.
FROM eclipse-temurin:17.0.4.1_1-jdk-focal AS arm32-jre-build
RUN cp -r /opt/java/openjdk /javaruntime
```

2022-11-01 13:39 UTC, lemeurherve commented on 17/bullseye/Dockerfile
> +FROM debian:bullseye-20221024 as build
```suggestion
FROM debian:bullseye-20221024 as build
```

2022-11-01 13:39 UTC, lemeurherve commented on docker-bake.hcl
> +
```suggestion
```

2022-11-01 13:39 UTC, lemeurherve commented on 17/bullseye/Dockerfile
> +
```suggestion
FROM build as default
COPY --from=jre-build /javaruntime $JAVA_HOME

FROM build as arm32
COPY --from=arm32-jre-build /javaruntime $JAVA_HOME

```

2022-11-02 13:44 UTC, gounthar commented on 17/bullseye/Dockerfile
> +FROM debian:bullseye-20221024 as build
```suggestion
FROM debian:bullseye-20221024 AS build
```

I'm being nit picky.

2022-11-02 13:48 UTC, gounthar commented on 17/bullseye/Dockerfile
> +FROM build as default
```suggestion
FROM build AS default
```
I'm being nit-picky.

2022-11-02 14:00 UTC, dduportal requested changes
Many thanks! This is really a nice job!

However, there are 2 (minor but blocking) changes to be made:

- The `target` field should be set outside the `args blocks`
- The `LABEL` filed in the `Dockerfile should be moved to the "common" debian stage.

2022-11-02 20:22 UTC, dduportal approved these changes
LGTM, great work!

2022-11-02 20:23 UTC, merged