Add Windows ltsc2022 images
jenkinsci/docker-agent pull request #441
Opened 2023-06-27 20:30 UTC by lemeurherve

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-06-28 01:27 UTC, lemeurherve commented on windows/windowsservercore-ltsc2022/Dockerfile
> +    $NewPath = $CurrentPath + $(';{0}\bin;C:\mingit\cmd' -f $env:JAVA_HOME) ; `
Note: [the lines 26 to 32](https://github.com/jenkinsci/docker-agent/pull/441/files#diff-5d04d09b0ca65a09875658793dcbf11f9d9297e0f9b762c0fcfac4e56905bc45R26-R32) using the method recommended in #429 and this one to fix the subsequent missing $JAVA_HOME in $PATH are the only differences between this file and the windows/windowsservercore-ltsc2019/Dockerfile file.

2023-06-28 01:27 UTC, lemeurherve commented on windows/nanoserver-ltsc2022/Dockerfile
> +FROM mcr.microsoft.com/powershell:nanoserver-ltsc2022
Note: the tag version in these images is the only difference between this file and the windows/nanoserver-1809/Dockerfile file.

2023-06-28 05:26 UTC, dduportal commented on updatecli/updatecli.d/remoting.yaml
> +    kind: file
Can you stick with the Dockerfile please? Using regexp (when there is a simple alternative) is a potential for mayhem and makes contribution harders.
Also, introducing this kind of change in a PR which is not about this topic is adding a lot of code to review and increase the potential of things going south.

The problem you want to solve here is worth a contribution to `updatecli` if you feel like it though (e.g. RFE to support multiple Dockerfiles for a given instruction change).

2023-06-28 05:31 UTC, dduportal requested changes
That is a nice work!

I got one important request though: could you update to avoid duplication as much as possible in the docker parts? You already did a good job in the `Jenkinsfile`, let's continue this effort (beside it avoid having Windows 2022 as an outside in this repo: all Linux are factorized)

That would mean:

- Passing the `2022` as env var to Docker compose
- Keep the `build-windows.yaml` Docker compose manifest for both 2019 and 2022
- Use the same `Dockerfile` for each 2019/2022 version (as your comment confirms,n there is no difference between Dockerfiles except the one you introduced that should be a separate PR because it solves another problem than "adding 2022 Windows")
  - Pass the Windows version as a build arg to differenciate 
  - Keep building on top of temurin for now (introducing a Windows 2022 that should have a certain behavior different than the Windows 2019 looks really weird to me as a user)

2023-06-28 22:53 UTC, lemeurherve commented
Note: I've extracted the refactoring of the Jenkinsfile in a separate PR: https://github.com/jenkinsci/docker-agent/pull/445

2023-07-07 17:02 UTC, dduportal commented
With #445 merged, you should be ready to rebase, fix conflicts and roll! Thanks a lot!

2023-07-07 17:19 UTC, lemeurherve commented
Replay with 7afbf7e in https://ci.jenkins.io/job/Packaging/job/docker-agent/view/change-requests/job/PR-441/79

2023-07-08 14:03 UTC, lemeurherve commented
Now successfully built, I've extracted the fix and some cleanup in https://github.com/jenkinsci/docker-agent/pull/458

2023-07-08 14:39 UTC, lemeurherve commented
Current changes for the image addition: https://github.com/jenkinsci/docker-agent/commit/17cb34a5910471687495b0cd0f7ac3f2f5aaa6ff

2023-07-10 10:14 UTC, dduportal approved these changes
Nice works 👏 

- Updatecli check is OK on the diff ✅ 
- ci.jenkins.io is building and testing the 2022 image in a 2022 agent (no container error)


@lemeurherve I'm merging. In order to get a release, we'll need to set up trusted.ci.jenkins.io so it can spin up 2022 agents: https://github.com/jenkins-infra/helpdesk/issues/3655

Then  a new tag in this repo will do the trick

2023-07-10 10:14 UTC, merged