Avoid building Windows Server Core on top of `eclipse-temurin` image
jenkinsci/docker-agent pull request #442
Opened 2023-06-28 15:55 UTC by lemeurherve

This PR switch from an `eclipse-temurin` base image to a `powershell:windowsservercore` one, a multi-stage image like it's done for nanoserver.

Close #429 

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-06-28 21:22 UTC, timja approved these changes

2023-07-01 13:59 UTC, dduportal requested changes
Nice work, ready to roll once my suggestion is taken in account

2023-07-01 13:59 UTC, dduportal commented on windows/windowsservercore-ltsc2019/Dockerfile
> +ARG JAVA_HOME="C:\openjdk-17"
```suggestion
ARG JAVA_HOME="C:\openjdk-17"
ENV JAVA_HOME=${JAVA_HOME}
```

The `eclipse-temurin` provides the `%JAVA_HOME%` environment variable to consumers: let's keep it :)

2023-07-01 15:23 UTC, dduportal approved these changes

2023-07-01 15:23 UTC, merged