feat(Linux): add Java 21
jenkinsci/docker-agent pull request #521
Opened 2023-10-12 07:56 UTC by lemeurherve

This PR adds Java 21 images and removes the previous `preview` Dockerfile.

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-10-12 09:19 UTC, gounthar reviewed
Maybe we should wait, then, until they become available.

2023-10-12 09:29 UTC, lemeurherve commented
> Maybe we should wait, then, until they become available.

I can rework my PR to keep linux-arm32 and linux-ppc64le as jdk21-**preview** images, WDYT?

2023-10-12 09:54 UTC, timja requested changes
~use a multi-arch image to retrieve the jdk please instead of fetching it via wget like we do in all other images~

I was looking at an old diff

2023-10-12 09:57 UTC, timja commented on docker-bake.hcl
> +target "debian_jdk21_preview" {
we should remove this and re-add when it's available, I don't think there's much point in shipping these preview tags in the meantime, it's confusing.

2023-10-12 09:57 UTC, timja commented on docker-bake.hcl
> +  platforms = ["linux/amd64", "linux/arm64"]
I would probably just wait a couple of days they probably won't take long to produce the other platforms?

2023-10-12 10:01 UTC, lemeurherve commented
> > Maybe we should wait, then, until they become available.
> 
> I can rework my PR to keep linux-arm32 and linux-ppc64le as jdk21-**preview** images, WDYT?
> 
> EDIT: done.

There aren't any binaries for these architectures in recent releases, and I'm not sure there will ever be.

To keep preview images for these specific architecture without blocking the major ones, I propose to use the (fixed) last release where they're available in https://github.com/jenkinsci/docker-agent/blob/f8e2ca6cf61fca89c90896d839c1dd0547aaff3a/debian/21/Dockerfile#L8-L19

WDYT?

2023-10-12 10:02 UTC, lemeurherve commented
We can also wait a few days.

2023-10-12 10:26 UTC, timja approved these changes

2023-10-12 12:06 UTC, gounthar commented
Thank you.
Here is the current status found `[here](https://github.com/adoptium/temurin/issues/8#issue-1933244087)`.
![image](https://github.com/jenkinsci/docker-agent/assets/116569/98ff353d-5f52-4b1d-a1fb-603c9e1e0c98)

2023-10-12 12:20 UTC, lemeurherve commented
> Thank you. Here is the current status found [here](https://github.com/adoptium/temurin/issues/8#issue-1933244087). 
Thanks for the link, quite useful!

> Could we wait for `arm32`, `ppc64le` [...] to go?

Yes, I'll keep this PR as draft until `arm32` & `ppc64le` images variants are ready.

>  and `x64 Windows`

Unrelated to this PR concerning Linux images.

We're already publishing amd64 Windows images (see https://hub.docker.com/r/jenkins/agent/tags?page=1&name=21), which AFAIU are the same architecture.

> I can't find the right link at the moment, but there is an explanation somewhere in a Temurin repo where they describe the different classes of platforms they support. I guess `s390x` is in the last group.

I've removed `s390x` target architecture for jdk21 as it won't be supported in commit https://github.com/jenkinsci/docker-agent/pull/521/commits/2d4b31908c3af3fb86018a623f61b32996b240d6

2023-10-20 06:48 UTC, lemeurherve commented
https://github.com/adoptium/temurin/issues/8 has been closed, and the October release status doesn't look good for the architectures we were waiting for: https://github.com/adoptium/temurin/issues/6

<img width="825" alt="image" src="https://github.com/jenkinsci/docker-agent/assets/91831478/2b10155e-33c8-4036-9350-0eadfe3cd248">

With these new elements at hand, are you OK if I restore a similar workaround as the one deployed in https://github.com/jenkinsci/docker/pull/1738 to keep the preview tags/images like in https://github.com/jenkinsci/docker-agent/pull/521/commits/2eae83657f4016b0d9b95ea7fefbbd6c89065318?

2023-10-20 10:44 UTC, MarkEWaite commented
I think that the workaround is a very reasonable compromise.

2023-10-20 10:59 UTC, dduportal commented
+1 with the workaround! Will be double justified as there is a ne EA release for `s390x` for instance, as pointed by @gounthar : https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.1%2B12-ea-beta

2023-10-20 12:19 UTC, gounthar commented
Yes, `ppc64le`, `s390x` and `armv7` are available for the JDK 21.0.1 early access.

2023-10-20 12:40 UTC, lemeurherve commented
I'll prepare the workaround, then as follow-up of this PR I'll prepare another one for updatecli manifests managing both type of versions like https://github.com/jenkinsci/docker/pull/1741

2023-10-22 17:16 UTC, lemeurherve commented
Included back the workaround, and also incorporated the same kind of preview (EA) release download URL fix as https://github.com/jenkinsci/docker/pull/1747

PR ready for review, to be squashed.

2023-10-22 19:00 UTC, dduportal approved these changes

2023-10-22 19:01 UTC, merged

2023-10-22 21:58 UTC, lemeurherve commented
> I'll prepare the workaround, then as follow-up of this PR I'll prepare another one for updatecli manifests managing both type of versions like [jenkinsci/docker#1741](https://github.com/jenkinsci/docker/pull/1741)

Updatecli manifests update addressed in https://github.com/jenkinsci/docker-agent/pull/536