fix(jdk21-preview): hardcoding `21` in the repo name of the EA release link
jenkinsci/docker-agent pull request #538
Opened 2023-10-23 08:43 UTC by lemeurherve

This PR fixes the preview (EA) release download link in the Dockerfile of the debian_jdk_21_preview image.

Related: https://github.com/jenkinsci/docker-agent/pull/537

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-10-23 09:48 UTC, dduportal requested changes
Wrong link: 
https://github.com/adoptium/temurin21.0.1-binaries/releases/download/jdk-21.0.1%2B12-ea-beta/OpenJDK21.0.1U-jdk_s390x_linux_hotspot_ea_21-0-1-12.tar.gz

Correct link: 
https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1%2B12-ea-beta/OpenJDK21U-jdk_s390x_linux_hotspot_ea_21-0-1-12.tar.gz


- Either you need to hardcode the 2nd occurence of `JAVA_MAJOR_VERSION` and remove all occurences (and the definition)
- Or eventually use my suggestion by fixing the `JAVA_MAJOR_VERSION` definition

2023-10-23 09:48 UTC, dduportal commented on debian/preview/Dockerfile
>    && JAVA_MAJOR_VERSION=$(echo $JAVA_VERSION | cut -d'+' -f1) \
```suggestion
  && JAVA_MAJOR_VERSION=$(echo $JAVA_VERSION | cut -d'+' -f1 | cut -d'.' -f1) \
```

WDYT of this change to ensure the `JAVA_MAJOR_VERSION` is always the first major digit (wether there are dots or not or '+' or not).

I've used this trick in https://github.com/jenkins-infra/packer-images/pull/860/files#diff-485e38775f798b1a8181ceada9148f140b6487f8bcadc39867338df791d06ca6R304-R307 FWIW.

- It would avoid the hardcoding
- It ensure that all occurence using `JAVA_MAJOR_VERSION` (there are two...) would work.

2023-10-23 12:47 UTC, lemeurherve commented on debian/preview/Dockerfile
> +  && JAVA_MAJOR_VERSION=$(echo $JAVA_VERSION | cut -d'.' -f1) \
🤦

2023-10-24 06:53 UTC, dduportal approved these changes

2023-10-24 08:13 UTC, merged

2023-10-24 08:21 UTC, lemeurherve commented
Hum... It failed on the primary branch :thinking:

https://github.com/jenkinsci/docker-agent/actions/runs/6624130432/job/17992491585

> ERROR: something went wrong in target "setJDK21PreviewVersionDockerBake" : "command error on refs/heads/updatecli_39548d6bb0215e91203e5365849207b3faf5504376b23ab629f00709c4208dd3: refusing to allow a GitHub App to create or update workflow `.github/workflows/release-drafter.yml` without `workflows` permission"

2023-10-24 08:21 UTC, lemeurherve commented
Running the action again without any issue 🤷