Bugfix: Fix regression where environment variables set to USER would be lowercased to user.
jenkinsci/docker-agent pull request #857
Opened 2024-08-14 19:09 UTC by aidanleuck

Fixes issue with environment variables named USER being set to user due to it being merged with the variable set in the Dockerfile.

### Testing done

### Submitter checklist
- [ x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x ] Ensure that the pull request title represents the desired changelog entry
- [ x ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira (Waiting for issue to be moved)
- [ x ] Link to relevant pull requests, esp. upstream and downstream changes
- [ N/A  ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-08-14 19:18 UTC, dduportal commented
Closes https://github.com/jenkinsci/docker-inbound-agents/issues/44

2024-08-14 19:18 UTC, dduportal approved these changes
Many thanks! that looks good!

2024-08-14 19:45 UTC, dduportal requested changes
@aidanleuck you also have to update the test harness: checks are failing due to this

2024-08-14 20:33 UTC, aidanleuck commented
@dduportal Thanks I fixed those tests. It appears it is still failing trying to download JDK, looking at past builds it appears this might be an intermittency as opposed to changes in my PR. Do we just need to keep running it again?

2024-08-16 08:01 UTC, dduportal approved these changes
LGTM!

2024-08-16 08:01 UTC, merged