WIP - [JENKINS-73703] Add Agent Images for UBI9
jenkinsci/docker-agent pull request #866
Opened 2024-08-29 19:27 UTC by adambkaplan

**Work In Progress - Feedback Requested**

Add agent and inbound-agent images for RHEL, based on UBI9. The base image is part of the UBI catalog and built on top of ubi-minimal. Therefore, the resulting images are free to redistribute anywhere (no subscription or terms agreement required).

This version of the Dockerfile chooses to use the openjdk runtime images as their base. These package the minimal JRE that Red Hat supports, avoiding the need to download and shrink a JDK from elsewhere on the internet. Note that Red Hat's definition of "minimal JRE" may differ from the Jenkins community's needs.

### Testing done

This is currently a draft pull request. I have been able to verify that the agent images build, but I have not completed an end to end test ensuring that the inbound agent image can talk to the Jenkins controller.

Feedback is requested on adding proper configuration in the Makefile and `docker-bake.hcl`. I also would like feedback on my choice to use the `openjdk-*-runtime` images as the base, rather than go the route of packaging a JRE from elsewhere (as is done in the other agent images).

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-08-29 19:54 UTC, dduportal commented
Thanks for the contribution !

a quick first feedback (need to take a look) : the Jenkins uses Temurin JDK so we would like to use it here as well.
Changing the JDK distribution for only one declination is a nightmare to manage : updates, che, patches, tests etc.

would you be willing to switch back to Temurin ?

2024-09-10 16:19 UTC, dduportal commented
Hi @adambkaplan , as discussed during the [Jenkins Platform SIG](https://www.jenkins.io/sigs/platform/) meeting today:

- We are good with adding UBI9 image for the agents
- But we won't accept a new JDK distribution other than Temurin (same model as other images) for the reasons I exposed on my previous comment (maintenance burden for us).

Is that OK for you to update your PR to match the JDK pattern of other images (current UBI or Debian)?

2024-09-11 18:01 UTC, adambkaplan commented
> Is that OK for you to update your PR to match the JDK pattern of other images (current UBI or Debian)?

Happy to match the JDK pattern for the controller's UBI image. I can completely understand the need to keep things in sync when it comes to testing, verification, and patching.

2024-09-11 18:23 UTC, gounthar commented
Thank you so much. 🤗

2024-09-12 14:02 UTC, adambkaplan commented
@gounthar @dduportal updated the PR to use the Temurin JDK, using the same scripts as the other agent images. Was able to verify the controller-agent connection works for the `inbound` flavor of the image locally.

I tried to update `docker-bake` and the README, but I'm a bit shakier on those as I don't have docker on my local machine. PTAL - after this next set of review I can squash commits and take this PR out of the draft state.

2024-09-12 16:29 UTC, gounthar commented
Thanks, I will have a look. 👍

2024-09-23 14:21 UTC, adambkaplan commented
@gounthar I have squashed commits, rebased this PR, and taken it out of draft state. PTAL.

2024-09-23 15:29 UTC, MarkEWaite commented
Thanks very much @adambkaplan !

I'm a little surprised at the addition of UBI 8 + Java 11.  Jenkins weekly has not supported Java 11 since 18 Jun 2024 ([Jenkins 2.463](https://www.jenkins.io/changelog/2.463/)).  Jenkins LTS 2.477.1 will not support Java 11 when it releases 30 Oct 2024.  Current Jenkins LTS (2.462.2) supports Java 11 and the 2 Oct 2024 Jenkins LTS (2.462.3) will support Java 11, but those will be the last LTS versions to support Java 11.

Jenkins does not support running a Jenkins agent with an older Java major version than the Java major version that is used on the controller.

That doesn't mean that we should not add a UBI 8 + Java 11 agent container, but the usable life of that container image seems much smaller than the UBI 9 + Java 17 and UBI 9 + Java 21 container images.

Is there a larger story behind the inclusion an agent image for UBI 8 + Java 11?

2024-09-23 18:57 UTC, adambkaplan commented
> Is there a larger story behind the inclusion of an agent image for UBI 8 + Java 11?

Not really. The present change set is meant to provide the same set of base OS + JREs for the agent that the community is providing for the main server. If the community plans on dropping UBI 8 support when Java 11 reaches EOL (effectively next week), then I agree it doesn't make sense to build an agent image now.

2024-09-23 19:26 UTC, timja commented
Could you drop it please

2024-09-23 21:48 UTC, adambkaplan commented
> Could you drop it please

Done!

2024-09-23 23:50 UTC, MarkEWaite requested changes

2024-09-23 23:50 UTC, MarkEWaite commented on README_agent.md
> +      * `jenkins/agent:latest-rhel-ubi8-jdk17`
I think this one needs to be ubi9 rather than ubi8.
```suggestion
      * `jenkins/agent:latest-rhel-ubi9-jdk17`
```

2024-09-23 23:50 UTC, MarkEWaite commented on docker-bake.hcl
> +# Return an array of RHEL UBI 8 platforms to use depending on the jdk passed as parameter
I think this needs to be a 9 as well.
```suggestion
# Return an array of RHEL UBI 9 platforms to use depending on the jdk passed as parameter
```

2024-09-23 23:50 UTC, MarkEWaite commented on rhel/ubi9/Dockerfile
> +FROM registry.access.redhat.com/ubi9/ubi:9.4-1214 as jre-build
A newer version was released recently.  Once this is merged, the automated updates should take care of it, but probably best to use most recent release from the start.
```suggestion
FROM registry.access.redhat.com/ubi9/ubi:9.4-1214.1726694543 as jre-build
```

2024-09-23 23:50 UTC, MarkEWaite commented on rhel/ubi9/Dockerfile
> +FROM registry.access.redhat.com/ubi9/ubi:9.4-1214 AS agent
Similar version update as earlier.
```suggestion
FROM registry.access.redhat.com/ubi9/ubi:9.4-1214.1726694543 AS agent
```

2024-09-23 23:50 UTC, MarkEWaite commented on rhel/ubi9/Dockerfile
> +
Remove the trailing spaces from the line
```suggestion

```

2024-09-23 23:50 UTC, MarkEWaite commented on rhel/ubi9/Dockerfile
> +
Remove trailing spaces
```suggestion

```

2024-09-23 23:50 UTC, MarkEWaite commented on rhel/ubi9/Dockerfile
> +
Remove trailing spaces
```suggestion

```

2024-09-23 23:50 UTC, MarkEWaite commented on rhel/ubi9/Dockerfile
> +
Remove trailing spaces.
```suggestion

```

2024-09-23 23:50 UTC, MarkEWaite commented on rhel/ubi9/Dockerfile
> +
Remove trailing spaces from the line
```suggestion

```

2024-09-23 23:50 UTC, MarkEWaite commented on rhel/ubi9/Dockerfile
> +      ca-certificates \
Remove trailing spaces
```suggestion
      ca-certificates \
```

2024-09-23 23:55 UTC, MarkEWaite approved these changes
All my remaining comments are optional.  This is ready to merge once CI job passes.

2024-09-23 23:55 UTC, MarkEWaite commented on docker-bake.hcl
> +# Note: Jenkins Docker controller only supports jdk-17 and jdk-21 for ubi9
Optional, replace "Docker" with "container"?
```suggestion
# Note: Jenkins controller container image only supports jdk-17 and jdk-21 for ubi9
```

2024-09-23 23:55 UTC, MarkEWaite commented on rhel/ubi9/Dockerfile
> +      "11."*) set -- "--strip-debug" "--compress=2" ;; \
I assume this is retained here so that the same content is in all the Dockerfile definitions.  That way we can remove them all at the same time when we drop support for Java 11.

2024-09-24 00:46 UTC, MarkEWaite submitted a review, later dismissed

2024-09-24 07:27 UTC, dduportal approved these changes

2024-09-24 09:53 UTC, lemeurherveCB reviewed
Small suggestions.

2024-09-24 09:53 UTC, lemeurherveCB commented on .github/dependabot.yml
> +
```suggestion
```

2024-09-24 09:53 UTC, lemeurherveCB commented on docker-bake.hcl
> +# Note: Jenkins controller container image only supports jdk-17 and jdk-21 for ubi9
```suggestion
# Note: Jenkins controller container image only supports jdk17 and jdk21 for ubi9
```
(nit)

2024-09-24 09:53 UTC, lemeurherveCB commented on rhel/ubi9/Dockerfile
> +FROM registry.access.redhat.com/ubi9/ubi:9.4-1214.1726694543 as jre-build
```suggestion
ARG UBI9_TAG="9.4-1214.1726694543"
FROM registry.access.redhat.com/ubi9/ubi:"${UBI9_TAG}" AS jre-build
```

2024-09-24 09:53 UTC, lemeurherveCB commented on rhel/ubi9/Dockerfile
> +FROM registry.access.redhat.com/ubi9/ubi:9.4-1214.1726694543 AS agent
```suggestion
FROM registry.access.redhat.com/ubi9/ubi:"${UBI9_TAG}" AS agent
```

2024-09-24 09:53 UTC, lemeurherveCB commented on docker-bake.hcl
If the `ARG UBI9_TAG` suggestion is accepted, it should also be defined as a variable here and passed to the corresponding target like what is done for `DEBIAN_RELEASE`.

2024-09-24 10:27 UTC, lemeurherveCB commented on rhel/ubi9/Dockerfile
> +FROM registry.access.redhat.com/ubi9/ubi:9.4-1214.1726694543 as jre-build
Having a separate ARG for this tag allows:
- to avoid duplication cf suggestion below
- to use https://updatecli.io to take care of its tracking and update instead of using Dependabot for that (more control and possibilities)

If you don't feel comfortable adding this don't worry we'll do it in a follow-up pull request.

2024-09-24 10:32 UTC, lemeurherveCB commented on rhel/ubi9/Dockerfile
> +FROM registry.access.redhat.com/ubi9/ubi:9.4-1214.1726694543 as jre-build
Example of updatecli manifest we're using to take care of Debian release: https://github.com/jenkinsci/docker-agent/blob/fafab56b78c83e9ef8cc27d62248cd8d3a3ec7af/updatecli/updatecli.d/debian.yaml

2024-09-24 10:36 UTC, lemeurherveCB commented on .github/dependabot.yml
> +
```suggestion
```
Cf https://github.com/jenkinsci/docker-agent/pull/866#discussion_r1773075772, removing this in favor of an updatecli manifest which can be added in a follow-up pull request.

2024-09-24 10:37 UTC, lemeurherveCB commented on .github/dependabot.yml
> +
Note that some content above should be removed too (unrelated to this PR)

2024-09-24 10:41 UTC, lemeurherveCB commented on .github/dependabot.yml
> +
> Note that some content above should be removed too (unrelated to this PR)

Addressed in https://github.com/jenkinsci/docker-agent/pull/877

2024-09-24 13:06 UTC, adambkaplan commented on rhel/ubi9/Dockerfile
> +FROM registry.access.redhat.com/ubi9/ubi:9.4-1214.1726694543 as jre-build
Accepting this suggestion since the other images are using similar mechanisms to keep the base image up to date.

2024-09-24 13:06 UTC, adambkaplan commented on docker-bake.hcl
Accepting the suggestion, thus I'll add a follow-up commit with the new variable.

2024-09-24 13:26 UTC, adambkaplan commented
Rebased and squashed commits down to 2 (preserving the decisions around UBI 8 and updatecli). Thanks everyone!

2024-09-24 13:40 UTC, dduportal approved these changes

2024-09-24 13:52 UTC, MarkEWaite approved these changes
Thanks!

2024-09-24 13:52 UTC, lemeurherveCB approved these changes

2024-09-24 13:55 UTC, merged